LineLength:
  Max: 120
AllCops:
  Exclude:
    - 'spec/**/*'
  DisplayCopNames: true
Rails:
  Enabled: true
Documentation:
  Enabled: false
Style/EndOfLine:
  Enabled: false
Metrics/MethodLength:
  Max: 12
